define({
	name:'com',
	params:[
		{
			name:'FACTORY_ID',
			title:'公司',
			index: 0,
			value: 1
		},
		{
			name:'UNIT_ID',
			title:'装置'
		},
		{
			name:'EQU_ID',
			title:'设备'
		},
		{
			name:'PRODUCT_ID',
			title:'产品'
		}
	],
	views:[
		{
			id:'2',
			title:'公司生产绩效',
			column:6,
			height:200,
			view:'view/pm/com-pm-operation-daily'
		},
		{
			id:'1',
			title:'产品KPI',
			column:6,
			height:200,
			view:'view/kpi/gauge'
		},
		{
			id:'3',
			title:'公司装置运行监控',
			column:6,
			height:200,
			view:'view/uom/com-unit-operation-status',
			scroll:'auto',
			url:{
				view:'view/uom/unit-status-details',
				height:'400',
				title:'装置运行详情',
				size:'modal-lg'
			}
		},
		{
			id:'4',
			title:'公司关键设备运行监控',
			height:200,
			view:'view/uom/com-equ-operation-status',
			scroll:'auto',
			url:{
				view:'view/dd/uom-equ-drilldown',
				height:'400',
				title:'关键设备详情',
				size:'modal-lg'
			}
		},
		{
			id:'5',
			title:'公司原料库存',
			column:6,
			height:140,
			scroll:'auto',
			view:'view/rm/com-raw-storage-status'
		},
		{
			id:'6',
			title:'罐区/仓库',
			height:260,
			view:'view/im/com-tanks-status',
			url:{
				view:'view/dd/im-tag-drilldown',
				height:'400',
				title:'储罐实时数据监控'
			}
		}
	]
});
