define({
	name:'com',
	views:[
		{
			id:'1',
			title:'运行总览',
			column:7,
			height:373,
			view:'view/jh/new_c1_operation',
			url:{
				view:'view/uom/unit-status-details',
				height:'400',
				title:'运行总览',
				size:'modal-lg'
			}
		},
		{
			id:'2',
			title:'生产绩效',
			height:230,
			view:'view/jh/new_c1_producation',
			scroll:'auto'
		},
		{
			id:'3',
			title:'KPI',
			column:5,
			height:373,
			view:'view/jh/new_c1_kpi',
			url:{
				view:'view/jh/new_c1_kpi_12d',
				height:'300',
				title:'KPI趋势'
			}
		},
		{
			id:'4',
			title:'能源消耗',
			height:230,
			view:'view/jh/new_c1_energy'
		}
	]
});