define({
	name:'pm',
	params:[
		{
			name:'PRODUCT_ID',
			title:'产品',
			index:0,
			value:10
		}
	],
	views:[
		{
			id:'1',
			title:'经济运行产品日报',
			column:6,
			height:654,
			view:'view/pm/pm-operation-daily',
			scroll:'auto'
		},
		{
			id:'2',
			title:'产品KPI',
			column:6,
			height:170,
			view:'view/kpi/gauge'
		},
		{
			id:'3',
			title:'产品产量30日趋势',
			height:179,
			view:'view/pm/production-trend-30d'
		},
		{
			id:'4',
			title:'产品库存30日趋势',
			height:179,
			view:'view/pm/production-storage-trend-30d',
			url:'http://10.99.2.230:8080/HUAYI/ReportServer?reportlet=productStockGraph.cpt&op=write'
		}
	]
});
